- name: Install fprintd
  ansible.builtin.package:
    name:
      - fprintd
      - libfprint-2-2
      - libpam-fprintd
    state: present

- name: Start fprintd
  ansible.builtin.service:
    name: fprintd
    enabled: true
    state: started
  register: result
  changed_when: false

- name: Check if pam module for fprintd is enabled
  ansible.builtin.command: grep --recursive 'fprintd' /etc/pam.d/
  register: result
  changed_when: false
  failed_when: false

- name: Update pam.d configs to allow auth w/ fingerprint
  when: result.rc != 0
  ansible.builtin.command: pam-auth-update --enable fprintd
  changed_when: true
