- name: Gather installed homebrew apps
  ansible.builtin.shell: |
    runuser - {{ main_user_name }} -c 'zsh -i -c "brew list --installed-on-request --full-name"'
  register: installed
  changed_when: false

- name: Install homebrew apps
  when: item not in installed.stdout_lines
  loop:
    - bat
    - direnv
    - fzf
    - gitui
    - k9s
    - kubectx
    - kubernetes-cli
    - ripgrep
    - starship
  ansible.builtin.shell: |
    runuser - {{ main_user_name }} -c 'zsh -i -c "brew install {{ item }}"'
  changed_when: true
  register: result
  retries: 3
  delay: 3
  until: result.rc == 0

- name: Custom aliases for homebrew apps
  loop:
    - root
    - "{{ main_user_name }}"
  ansible.builtin.include_tasks: tasks.yaml
