- name: lookup user name of main user
  ansible.builtin.shell: id --name --user 1000
  register: result
  changed_when: false

- name: save user name of main user
  ansible.builtin.set_fact: MAIN_USER_NAME="{{result.stdout}}"
